name: Android CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug
          
      - uses: actions/upload-artifact@v3
        with:
          name: sweater-apk
          path: app/build/outputs/apk/debug/*.apk
